print ("append")
print ("ejercicio 1")
print (                             )
lista = []
lista.append (7)
print (lista)
print (                             )
print ("ejercicio 2")
print (                             )
nombres = ['ana','luis']
nombres.append ("carlos")
print (nombres)
print (                             )
print ("insert")
print ("ejercicio 1")
print (                             )
numeros = [1,2,3,4,5]
numeros.insert (0,"99")
print (numeros)
print (                             )
print ("ejercicio 2")
print (                             )
colores = ["azul","verde"]
colores.insert (1,"rojo")
print (colores)
print (                             )
print ("extended")
print ("ejercicio 1")
print (                             )
num = [2,1,4,5,3]
num.extend ([0,3,5,1])
print (num)
print (                             )
print ("ejercicio 2")
print (                             )
lista = ["a","b","c"]
lista.extend (["ok"])
print (lista)
print (                             )
print ("remove")
print ("ejercicio1")
print (                             )
frutas = ['manzana','peras','uvas']
frutas.remove ("uvas")
print (frutas)
print (                             )
print ("ejercicio 2")
numeros = [1,2,3,4,5,6]
numeros.remove (3)
print (numeros)
print (                             )
print ("pop")
print ("ejercicio 1")
print (                             )
elemento = [1,2,3,4,5,6]
elemento.pop (5)
print (elemento)
print (                             )
print ("ejercicio 2")
print (                             )
lista = ["dia","noche","tarde"]
lista.pop(0)
print (lista)
print (                             )
print ("clear")
print ("ejercicio 1")
print (                             )
lista = [1,2]
lista.clear ()
print (lista)
print (                             )
print ("ejercicio 2")
print (                             )
lista = []
lista.append (input("dame un elemento: "))
lista.append (input("dame un producto: "))
lista.append (input("dame un producto: "))
lista.append (input("dame un producto: "))
lista.append (input("dame un producto: "))
print (lista)
lista.clear()
print (lista)
print (                             )
print ("index")
print ("ejercicio 1")
print (                             )
producto = ["manzana",'pera','truifruti']
print (producto.index ("pera"))
print (                             )
print ("ejercicio 2")
print (                             )
numeros = [1,2,3,4,5,6,7,8,9]
print (numeros.index(6))
print (                             )
print ("count")
print ("ejercicio 1")
print (                             )
condena = [1,1,1,2,2,3,1,]
print (condena.count(1))
print (                             )
print ("ejercicio 2")
print (                             )
lista = ['a','s','a','a','a']
print (lista.count('a'))
print (                             )
print ("sort")
print ("ejercicio 1")
print (                             )
ordenar=[1,5,22,3,2,4]
ordenar.sort ()
print (ordenar)
print (                             )
print ("ejercicio 2")
print (                             )
ordenar = ['a','c','p','b','w']
ordenar.sort ()
print (ordenar)
print (                             )
print ("reverse")
print ("ejercicio 1")
print (                             )
lista =[1,2,3,4,5,6,7]
lista.reverse ()
print (lista)
print (                             )
print ("ejercicio 2")
print (                             )
cuento = ['inicio','nudo','desenlace']
cuento.reverse ()
print (cuento)
print (                             )
print ("copy")
print ("ejercicio 1")
print (                             )
lista = [1,2,3,4]
nueva_lista = lista.copy()
print (lista)
print (nueva_lista)
print (                             )
print ("ejercico 2")
print (                             )
lista = ['a','b','c']
nueva = lista.copy()
nueva.append("d")
print (lista)
print (nueva)